FROM python:3.12

RUN pip3 install pytest==8.3.4

RUN pip3 install requests==2.32.3

RUN pip3 install typing

RUN pip3 install logging==0.4.9.6

RUN pip3 install xmltodict

RUN pip3 install flask

COPY iss_tracker.py /code/iss_tracker.py

COPY test_iss_tracker.py /code/test_iss_tracker.py

RUN chmod +rx /code/iss_tracker.py

RUN chmod +rx /code/test_iss_tracker.pys

ENV PATH="/code:$PATH"